controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100

  trigger_calibration_controller:
    type: rm_calibration_controllers/JointCalibrationController
    joint: trigger_joint
    actuator: [ trigger_joint_motor ]
    search_velocity: 3.1415
    threshold: 0.001
    pid: { p: 0.8, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }


  chassis_controller:
    type: rm_chassis_controllers/MecanumController
    # ChassisBase
    publish_rate: 100
    enable_odom_tf: true
    publish_odom_tf: false
    power:
      effort_coeff: 3.9
      vel_coeff: 0.00855
      power_offset: -9.8
    twist_angular: 0.5233
    timeout: 0.1
    pid_follow: { p: 5, i: 0, d: 0.8, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    twist_covariance_diagonal: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.001 ]

    # MecanumController
    wheel_base: 0.400
    wheel_track: 0.370

    wheel_radius: 0.07625

    left_front:
      joint: "left_front_wheel_joint"
      pid: { p: 0.8, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    right_front:
      joint: "right_front_wheel_joint"
      pid: { p: 0.8, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    left_back:
      joint: "left_back_wheel_joint"
      pid: { p: 0.8, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    right_back:
      joint: "right_back_wheel_joint"
      pid: { p: 0.8, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }


  orientation_controller:
    type: rm_orientation_controller/Controller
    publish_rate: 100
    name: "gimbal_imu"
    frame_source: "odom"
    frame_target: "base_link"

  gimbal_controller:
    type: rm_gimbal_controllers/Controller
    yaw:
      joint: "yaw_joint"
      pid: { p: 10, i: 0, d: 1.1, i_clamp_max: 0.3, i_clamp_min: -0.3, antiwindup: true, publish_state: true }
      k_chassis_vel: 0.04
    pitch:
      joint: "pitch_joint"
      pid: { p: 10.0, i: 0, d: 0.25, i_clamp_max: 0, i_clamp_min: 0, antiwindup: true, publish_state: true }
    imu_name: "gimbal_imu"
    feedforward:
      gravity: 0.0
      enable_gravity_compensation: false
      mass_origin: [ 0.0,0.0,0.0 ]
    bullet_solver:
      resistance_coff_qd_10: 0.45
      resistance_coff_qd_15: 1.0
      resistance_coff_qd_16: 0.7
      resistance_coff_qd_18: 0.55
      resistance_coff_qd_30: 3.0
      g: 9.81
      delay: 0.1
      dt: 0.001
      timeout: 0.001
      publish_rate: 50

  shooter_controller:
    type: rm_shooter_controllers/Controller
    publish_rate: 50
    friction_left:
      joint: "left_friction_wheel_joint"
      pid: { p: 0.001, i: 0.01, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
    friction_right:
      joint: "right_friction_wheel_joint"
      pid: { p: 0.001, i: 0.01, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
    trigger:
      joint: "trigger_joint"
      pid: { p: 80, i: 0.0, d: 1.6, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true, publish_state: true }
    push_per_rotation: 6
    push_qd_threshold: 0.90
    block_effort: 4.8
    block_speed: 0.1
    block_duration: 0.05
    block_overtime: 0.5
    anti_block_angle: 0.5
    anti_block_threshold: 0.1
    qd_10: 370.0
    qd_16: 580.0
