standalone_camera:
  image_width: 1280
  image_height: 1024
  pixel_format: bgr8
  camera_info_url: ''
  camera_name: standalone_camera
  camera_frame_id: camera_optical_frame
  camera_sn: KE0220040170
  enable_imu_trigger: false