rm_track:
  filters:
    - type: distance_filter
      basic_range: [ 0., 1. ]
      double_check_range: [ 4.0, 6.0 ]
  selectors:
    - last_armor
    - same_id_armor
    - static_armor
    - closest_armor
  linear_kf:
    Q: [ 1000.0, 1000.0, 1000.0, 1000.0, 1000.0, 1000.0 ]
    R: [ 1, 1, 1 ]
    debug: true
