rm_hw:
  bus:
    - can0
    - can1
  loop_frequency: 1000
  cycle_time_error_threshold: 0.001
  thread_priority: 95
  # Configurations of the actuators
  actuators:
    left_wheel_joint_motor:
      bus: can0
      id: 0x201
      type: rm_3508
      lp_cutoff_frequency: 60
    right_wheel_joint_motor:
      bus: can0
      id: 0x202
      type: rm_3508
      lp_cutoff_frequency: 60
    left_momentum_block_joint_motor:
      bus: can0
      id: 0x203
      type: rm_3508
      lp_cutoff_frequency: 60
    right_momentum_block_joint_motor:
      bus: can0
      id: 0x204
      type: rm_3508
      lp_cutoff_frequency: 60
  imus:
    gimbal_imu:
      frame_id: base_imu
      bus: can1
      id: 0x100
      orientation_covariance_diagonal: [ 0.0012, 0.0012, 0.0012 ]
      angular_velocity_covariance: [ 0.0004, 0.0004, 0.0004 ]
      linear_acceleration_covariance: [ 0.01, 0.01, 0.01 ]
      angular_vel_offset: [ -0.005, 0.001, -0.0015 ]
      angular_vel_coeff: 0.0010652644
      accel_coeff: 0.0017944335
      temp_coeff: 0.125
      temp_offset: 23.0
      filter: complementary
      do_bias_estimation: false
      do_adaptive_gain: true
      gain_acc: 0.0003
